=== Gelio/the-project-game/schemas/configs/game-master-config.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://the-project-game.net/schema/configs/game-master-config.json",

  "type": "object",
  "title": "GameMasterConfig",

  "properties": {
    "serverHostname": {
      "type": "string",
      "format": "hostname"
    },
    "serverPort": {
      "$ref": "../common/common-defs.json#/definitions/port"
    },
    "gameName": {
      "type": "string"
    },
    "gameDescription": {
      "type": "string"
    },
    "gamesLimit": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "teamSizes": {
      "$ref": "../common/team-sizes.json#"
    },
    "pointsLimit": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "boardSize": {
      "type": "object",
      "properties": {
        "x": {
          "$ref": "common/common-defs.json#/definitions/positiveInteger"
        },
        "taskArea": {
          "$ref": "common/common-defs.json#/definitions/positiveInteger"
        },
        "goalArea": {
          "$ref": "common/common-defs.json#/definitions/positiveInteger"
        }
      },
      "required": ["x", "taskArea", "goalArea"]
    },
    "shamChance": {
      "type": "number",
      "minimum": 0,
      "maximum": 1
    },
    "generatePiecesInterval": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "piecesLimit": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "resultFileName": {
      "type": "string"
    },
    "actionDelays": {
      "$ref": "../common/action-delays.json#"
    },
    "timeout": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "registrationTriesLimit": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    },
    "registerGameInterval": {
      "$ref": "../common/common-defs.json#/definitions/positiveInteger"
    }
  },

  "required": [
    "serverHostname",
    "serverPort",
    "gameName",
    "gameDescription",
    "gamesLimit",
    "teamSizes",
    "pointsLimit",
    "boardSize",
    "shamChance",
    "generatePiecesInterval",
    "piecesLimit",
    "resultFileName",
    "actionDelays",
    "timeout",
    "registrationTriesLimit",
    "registerGameInterval"
  ]
}

=== Gelio/the-project-game/src/game-master.config.json
{
  "serverHostname": "localhost",
  "serverPort": 4200,
  "gameName": "the project game",
  "gameDescription": "High sham chance, many pieces",
  "gamesLimit": 5,
  "teamSizes": {
    "1": 5,
    "2": 5
  },
  "pointsLimit": 20,
  "boardSize": {
    "x": 30,
    "taskArea": 30,
    "goalArea": 10
  },
  "shamChance": 0.8,
  "generatePiecesInterval": 3000,
  "piecesLimit": 15,
  "resultFileName": "result.json",
  "actionDelays": {
    "move": 4000,
    "pick": 1000,
    "discover": 2500,
    "destroy": 1000,
    "test": 3000,
    "communicationRequest": 4000,
    "communicationAccept": 4000,
    "tryPiece": 4000
  },
  "timeout": 10000,
  "registrationTriesLimit": 5,
  "registerGameInterval": 10000
}
