=== Gelio/the-project-game/schemas/discovery-response.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://the-project-game.net/schema/discovery-response.json",

  "type": "object",
  "title": "DiscoveryResponse",

  "properties": {
    "type": {
      "const": "DISCOVERY_RESPONSE"
    },
    "senderId": {
      "$ref": "common/entity-ids.json#/definitions/gameMasterId"
    },
    "recipientId": {
      "$ref": "common/entity-ids.json#/definitions/playerId"
    },
    "payload": {
      "type": "object",
      "properties": {
        "tiles": {
          "type": "array",
          "items": {
            "type": "object",
            "properties": {
              "x": {
                "type": "number",
                "minimum": 0
              },
              "y": {
                "type": "number",
                "minimum": 0
              },
              "playerId": {
                "$ref": "common/entity-ids.json#/definitions/playerId"
              },
              "piece": {
                "type": "boolean"
              },
              "distanceToClosestPiece": {
                "type": "number",
                "minimum": -1
              }
            },

            "additionalProperties": false,
            "required": ["x", "y", "playerId", "piece", "distanceToClosestPiece"]
          },
          "minItems": 4,
          "maxItems": 9,
          "uniqueItems": true
        },
        "timestamp": {
          "type": "number"
        }
      },

      "additionalProperties": false,
      "required": ["tiles", "timestamp"]
    }
  },

  "additionalProperties": false,
  "required": ["type", "senderId", "recipientId", "payload"]
}

=== Gelio/the-project-game/schemas/example-messages/discovery-response.json
{
  "$schema": "../discovery-response.json",

  "type": "DISCOVERY_RESPONSE",
  "senderId": "GAME_MASTER",
  "recipientId": "uuid",
  "payload": {
    "timestamp": 1515941821,
    "tiles": [
      {
        "x": 5,
        "y": 3,
        "playerId": "p5",
        "piece": true,
        "distanceToClosestPiece": -1
      },
      {
        "x": 6,
        "y": 3,
        "playerId": "p4",
        "piece": false,
        "distanceToClosestPiece": 1
      },
      {
        "x": 7,
        "y": 3,
        "playerId": "p3",
        "piece": false,
        "distanceToClosestPiece": 2
      },
      {
        "x": 5,
        "y": 2,
        "playerId": null,
        "piece": false,
        "distanceToClosestPiece": 1
      },
      {
        "x": 6,
        "y": 2,
        "playerId": "p1",
        "piece": false,
        "distanceToClosestPiece": 2
      },
      {
        "x": 6,
        "y": 2,
        "playerId": "p1",
        "piece": false,
        "distanceToClosestPiece": 2
      }
    ]
  }
}
