=== Gelio/the-project-game/schemas/game-started.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://the-project-game.net/schema/game-started.json",
  "definitions": {
    "singleTeamInfo": {
      "type": "object",
      "properties": {
        "players": {
          "type": "array",
          "items": {
            "type": "string",
            "minItems": 1
          }
        },
        "leaderId": {
          "type": "string"
        }
      },
      "required": ["players", "leaderId"]
    }
  },
  "type": "object",
  "title": "GameStarted",
  "description": "Message sent to Player when both teams are full and the game is started",
  "properties": {
    "type": {
      "const": "GAME_STARTED"
    },
    "senderId": {
      "$ref": "common/entity-ids.json#/definitions/gameMasterId"
    },
    "recipientId": {
      "$ref": "common/entity-ids.json#/definitions/playerId"
    },
    "payload": {
      "type": "object",
      "properties": {
        "teamInfo": {
          "type": "object",
          "properties": {
            "1": {
              "$ref": "#/definitions/singleTeamInfo"
            },
            "2": {
              "$ref": "#/definitions/singleTeamInfo"
            }
          },
          "required": ["1", "2"]
        }
      },
      "required": ["teamInfo"]
    }
  },
  "required": ["type", "senderId", "recipientId", "payload"]
}

=== Gelio/the-project-game/schemas/example-messages/game-started.json
{
  "$schema": "../game-started.json",

  "type": "GAME_STARTED",
  "senderId": "GAME_MASTER",
  "recipientId": "123e4567-e89b-12d3-a456-426655440000",
  "payload": {
    "teamInfo": {
      "1": {
        "players": ["123e4567-e89b-12d3-a456-426655440000", "223e4567-e89b-12d3-a456-426655440000"],
        "leaderId": "123e4567-e89b-12d3-a456-426655440000"
      },
      "2": {
        "players": ["323e4567-e89b-12d3-a456-426655440000", "423e4567-e89b-12d3-a456-426655440000"],
        "leaderId": "323e4567-e89b-12d3-a456-426655440000"
      }
    }
  }
}
