=== Gelio/the-project-game/schemas/list-games-response.json
{
  "$schema": "http://json-schema.org/draft-07/schema",

  "type": "object",
  "title": "ListGamesResponse",
  "description": "Response containing the list of games",

  "properties": {
    "type": {
      "const": "LIST_GAMES_RESPONSE"
    },
    "senderId": {
      "$ref": "common/entity-ids.json#/definitions/communicationServerId"
    },
    "recipientId": {
      "$ref": "common/entity-ids.json#/definitions/playerId"
    },
    "payload": {
      "type": "object",
      "properties": {
        "games": {
          "type": "array",
          "items": {
            "$ref": "common/game-definition.json"
          }
        }
      },
      "required": ["games"]
    }
  },

  "required": ["type", "senderId", "recipientId", "payload"]
}

=== Gelio/the-project-game/schemas/example-messages/list-games-response.json
{
  "$schema": "../list-games-response.json",

  "type": "LIST_GAMES_RESPONSE",
  "senderId": "COMMUNICATION_SERVER",
  "recipientId": "uuid",
  "payload": {
    "games": [
      {
        "name": "Default",
        "description": "This field is for UI purposes",
        "teamSizes": {
          "1": 5,
          "2": 5
        },
        "boardSize": {
          "x": 40,
          "taskArea": 40,
          "goalArea": 2
        },
        "goalLimit": 15,
        "delays": {
          "move": 4000,
          "pick": 1000,
          "discover": 2500,
          "destroy": 1000,
          "test": 3000,
          "communicationRequest": 4000,
          "communicationAccept": 4000,
          "place": 4000
        }
      },
      {
        "name": "Quick",
        "description": "A quick-paced game on a small field",
        "teamSizes": {
          "1": 3,
          "2": 3
        },
        "boardSize": {
          "x": 15,
          "taskArea": 10,
          "goalArea": 2
        },
        "goalLimit": 10,
        "delays": {
          "move": 2000,
          "pick": 500,
          "discover": 1250,
          "destroy": 500,
          "test": 2000,
          "communicationRequest": 1000,
          "communicationAccept": 1000,
          "place": 1000
        }
      }
    ]
  }
}
