=== Gelio/the-project-game/schemas/positive-communication-response-gm-asker.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://the-project-game.net/schema/positive-communication-response-gm-asker.json",

  "type": "object",
  "title": "PositiveCommunicationResponseGmAsker",
  "description": "Positive communication response from Game Master to asker",

  "properties": {
    "type": {
      "const": "COMMUNICATION_RESPONSE"
    },
    "senderId": {
      "$ref": "common/entity-ids.json#/definitions/gameMasterId"
    },
    "recipientId": {
      "$ref": "common/entity-ids.json#/definitions/playerId"
    },
    "payload": {
      "type": "object",
      "properties": {
        "senderPlayerId": {
          "$ref": "common/entity-ids.json#/definitions/playerId"
        },
        "accepted": {
          "const": true
        },
        "board": {
          "type": "array",
          "items": {
            "$ref": "common/tile.json#"
          },
          "minItems": 1
        }
      },
      "required": ["senderPlayerId", "accepted", "board"]
    }
  },
  "required": ["type", "senderId", "recipientId", "payload"]
}

=== Gelio/the-project-game/schemas/example-messages/positive-communication-response-gm-asker.json
{
  "$schema": "../positive-communication-response-gm-asker.json",

  "type": "COMMUNICATION_RESPONSE",
  "senderId": "GAME_MASTER",
  "recipientId": "asker",
  "payload": {
    "senderPlayerId": "asked",
    "accepted": true,
    "board": [
      {
        "distanceToPiece": 5,
        "hasCompletedGoal": false,
        "piece": {
          "isSham": true,
          "wasTested": true
        },
        "playerId": null,
        "timestamp": 1515941794
      },
      {
        "distanceToPiece": 4,
        "hasCompletedGoal": false,
        "piece": null,
        "playerId": "someuuid",
        "timestamp": 1515941821
      }
    ]
  }
}
